include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
    - "**/*.gr.dart"
    
  errors:
    # Make common issues loud
    unused_import: error
    dead_code: warning
    deprecated_member_use: warning
    invalid_use_of_protected_member: error
    use_build_context_synchronously: warning

linter:
  rules:
    # Imports / structure
    always_use_package_imports: true
    directives_ordering: true
    sort_child_properties_last: true

    # Flutter best practices
    use_key_in_widget_constructors: true
    prefer_const_constructors: true
    prefer_const_literals_to_create_immutables: true

    # Code style
    prefer_single_quotes: true
    avoid_print: true

    # Optional (keep if you like tighter style)
    unnecessary_this: true
    sort_constructors_first: true

    # Recommended adds
    prefer_final_locals: true
    prefer_final_fields: true
    unawaited_futures: true
    flutter_style_todos: true
    avoid_renaming_method_parameters: true
    avoid_unused_constructor_parameters: true
