// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAT7GO4I--Jl57vqAQfFM9V_I-D_j0mOJM',
    appId: '1:494333074686:web:e20df9bf00f9c9ab1c19af',
    messagingSenderId: '494333074686',
    projectId: 'flutter-havenote-app',
    authDomain: 'flutter-havenote-app.firebaseapp.com',
    storageBucket: 'flutter-havenote-app.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAAQmiBfLql_WgHszPogE6geUtkjiz-0N4',
    appId: '1:494333074686:android:3b0aef49ef0ec9eb1c19af',
    messagingSenderId: '494333074686',
    projectId: 'flutter-havenote-app',
    storageBucket: 'flutter-havenote-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBtGYPlKcV8zvxI0P_r0uMauyfxJNFjopc',
    appId: '1:494333074686:ios:a8216cf2874d1c391c19af',
    messagingSenderId: '494333074686',
    projectId: 'flutter-havenote-app',
    storageBucket: 'flutter-havenote-app.firebasestorage.app',
    iosBundleId: 'com.example.havenote',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBtGYPlKcV8zvxI0P_r0uMauyfxJNFjopc',
    appId: '1:494333074686:ios:a8216cf2874d1c391c19af',
    messagingSenderId: '494333074686',
    projectId: 'flutter-havenote-app',
    storageBucket: 'flutter-havenote-app.firebasestorage.app',
    iosBundleId: 'com.example.havenote',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAT7GO4I--Jl57vqAQfFM9V_I-D_j0mOJM',
    appId: '1:494333074686:web:6450677382ac35a31c19af',
    messagingSenderId: '494333074686',
    projectId: 'flutter-havenote-app',
    authDomain: 'flutter-havenote-app.firebaseapp.com',
    storageBucket: 'flutter-havenote-app.firebasestorage.app',
  );
}
